### ISSUE TITLE
Make Balena USEPROXY=true, currently are false

### ISSUE THREAD

**Issue by 452** [opengs/uashield#207]
Something wrong with the configuration, I have double-checked, by default value false
https://github.com/opengs/uashield/blob/868a43ef0a5b0ca24e8d83eded1af3fef5ee56c4/balena.yml#L20

![image](https://user-images.githubusercontent.com/1583753/161853083-6d4af9e7-98d9-478a-894a-177f37d4f93d.png)

**Comment by opengs** [comment]
Yeap. Same with workers count. We took script from https://www.balena.io/docs/learn/deploy/deploy-with-balena-button/
```yml

name: balenaSound
type: sw.application
description: >-
  Build a single or multi-room streamer for an existing audio device using a
  Raspberry Pi! Supports Bluetooth, Airplay and Spotify Connect
assets:
  repository:
    type: blob.asset
    data:
      url: 'https://github.com/balenalabs/balena-sound'
  logo:
    type: blob.asset
    data:
      url: >-
        https://raw.githubusercontent.com/balenalabs/balena-sound/master/logo.png
data:
  applicationEnvironmentVariables:
    - SOUND_VOLUME: 75
    - AUDIO_OUTPUT: AUTO
  defaultDeviceType: raspberry-pi
  supportedDeviceTypes:
    - raspberry-pi
    - raspberry-pi2
    - raspberrypi3
    - raspberrypi4-64
    - fincm3
    - intel-nuc
version: 3.5.2
```
very strange, that this doesnt work.
